### PR TITLE
Table column reorder by drag & drop

### PR DESCRIPTION
**Pull request by msankaran0712**
- Enabled drag and drop on the table headers and added examples
- Moved some of the code in DataTable.tsx into custom hooks
- Some minor improvements

Note:
Dragging/Dropping is disabled for all the columns by default, we enable drag/drop through the component props.
In the example, we enabled it for all the columns except for the last column "Profile Progress" hence it can neither be dragged nor be dropped, the only exception is the "Status" column because it was already in that location.  

@egunther39 @enowak1031 @soniakaukonen Please review the above functionality.

Preview:
https://deploy-preview-155--modus-react-bootstrap.netlify.app/components/tables/#ColumnReorderingbyDragandDrop

### CODE REVIEW

**Review by soniakaukonen — APPROVED** [review]
Tried it out, works fine but one principle is unclear to me (I am sorry if I don't know enough background in it yet). Red appears when the drag and drop action is not allowed, e.g dragging the Status in front of Profile Progress Status and trying to drop it there (because it is already its current location or other reason?). Any others can be dragged to the location they are already located in the moment of drag&drop. So I would like to understand when it is not allowed.

**Comment by msankaran0712** [comment]
> Tried it out, works fine but one principle is unclear to me (I am sorry if I don't know enough background in it yet). Red appears when the drag and drop action is not allowed, e.g dragging the Status in front of Profile Progress Status and trying to drop it there (because it is already its current location or other reason?). Any others can be dragged to the location they are already located in the moment of drag&drop. So I would like to understand when it is not allowed.

Dragging/Dropping is disabled for all the columns by default, using the props that I mentioned in the description we can enable it for the column we wish to. 
In this example we disabled drag and drop for the last column "Profile Progress" hence it can neither be dragged nor be dropped, the only exception is the "Status" column because it was already in that location.

**Review by enowak1031 — CHANGES_REQUESTED** [review]
The cursor on hover on movable columns should be a hand (not an arrow).

**Comment by msankaran0712** [comment]
Create a new PR

**Pull request closed without merging**
