### PR TITLE
Test content tree with indicator

### PR DESCRIPTION
**Pull request by msankaran0712**
- Add an example to show an indicator in Tree Item when expanded.
- Also fixed DataTable with checkbox column width issue
- And updated the components from modus-react-bootstrap for latest API details

Note: 
1. Please ignore the changes on the folder src/api-docs/modus-react-bootstrap as it is a mere copy paste from the other repo
2. Added `trimbleinc-modus-react-bootstrap-1.1.0.tgz`  inorder to test the latest changes from modus-react-bootstrap which is not published yet and will be removed after the release

Previews: 
https://deploy-preview-219--modus-react-bootstrap.netlify.app/components/content-tree/#Treewithindicatorforexpand
https://deploy-preview-219--modus-react-bootstrap.netlify.app/components/tables/#TablewithCheckBoxRowSelection

Fixes # [79](https://github.com/trimble-oss/modus-react-bootstrap/issues/79), [76](https://github.com/trimble-oss/modus-react-bootstrap/issues/76)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?
Manual Testing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have tested my changes across the different browsers we support
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by coliff — CHANGES_REQUESTED** [review]
On the 'Tree with indicator for expand' demo there us an invisible 'Drag the item' div.
- This should be removed from this example It would cause accessibility issues.
- Can we also replace the inline style `display: inline-flex;` with class `d-inline-flex`.
- There's an empty `item-indent` class. Can that be removed? Instead use utility class `pl-0` ?

**Comment by msankaran0712** [comment]
@coliff Please check now, review comments are fixed now.

**Review by coliff — COMMENTED** [review]
what is the `trimbleinc-modus-react-bootstrap-1.1.0.tgz` file for?
Should it be checked into git?

**Comment by msankaran0712** [comment]
> what is the `trimbleinc-modus-react-bootstrap-1.1.0.tgz` file for? Should it be checked into git?

it is a temporary modus-react-bootstrap dependency meant only for testing and PRs, should be removed when merging the changes to the main branch and post-release of modus-react-bootstrap v1.1.1.

**Review by enowak1031 — APPROVED** [review]

**Pull request closed without merging**
