### PR TITLE
Fix display heading font sizes

### PR DESCRIPTION
**Pull request by msankaran0712**
Made the Home page big text "Modus React Bootstrap" sized the same way as the Modus Bootstrap site 
Did the samething what is done here:
https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/pull/85/files#diff-857e28799841562c3cd4bd04671992708f4aafc341988ad1ccc80903e3dc1986

### CODE REVIEW

**Comment by coliff** [comment]
This isn't right:
image

The display-2 font size is 5.5rem when it should be 2.5rem.
(See https://modus.trimble.com/css/modus-1.4.0.css)

**Comment by msankaran0712** [comment]
@enowak1031 @coliff moving this PR to draft for now and reopen it when the modus bootstrap version which is tied to the modus-react-bootstrap is updated

**Comment by coliff** [comment]
Modus Bootstrap is updated to 1.4.0 already:
https://www.jsdelivr.com/package/npm/@trimbleinc/modus-bootstrap

**Comment by msankaran0712** [comment]
fixing in https://github.com/trimble-oss/website-modus-react-bootstrap.trimble.com/pull/166

**Pull request closed without merging**
